baseURL = "https://apinter.github.io/"
languageCode = "en-us"
title = "YAL/TB"
theme="archie"
copyright = "GNU FDL 1.3"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="dark"
	useCDN=false
	subtitle = "Yet Another Linux/Tech Blog - mostly my notes though"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/apinter"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/adathorium"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
